# This is a basic workflow to help you get started with GitHub Actions

name: CI

# Set strict permissions to improve security
permissions:
  contents: read
  actions: read
  pull-requests: none
  statuses: none

on:
  # Triggers the workflow on push or pull request events to the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows manual trigger from the GitHub Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a one-line shell command
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a multi-line shell command
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
